# YAML configuration for extract_spectra.py

multithread : False
clobber : True

# Path to the 2D echelle FITS image
fits_file: /media/koi368/minerva_spec/20250707/20250707T200946_HD172051.FIT

# List of trace files (NPZ format) and their labels
trace_files:
  - cal/Cal.trace.npz
  - cal/T4.trace.npz
  - cal/T5.trace.npz

trace_names:
  - Cal
  - T4
  - T5

trace_vel_offsets:
  - 0
  - 13.275
  - 13.309


# Per fiber extraction width (pix)
extraction_width: 5.0

# Background mask units: 'fwhm' uses multiples of fitted FWHM; 'pix' uses fixed pixels
unit: zeros

# Mask half-width (in units defined above) to exclude background regions
background_mask: 3.0

# Order of polynomial for background fitting (0 = median background)
bkorder: 1

iodinetemplate : cal/iodinestandard.fits
rawiodinefits : raw_fibflats/Calib-Iodine-master.FIT
# Output FITS file to write all extracted spectra
output: extracted_spectra.fits


